import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const page = await browser.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(`PAGEERROR: ${e.message}`));
page.on('console', (m) => { if (m.type() === 'error') errors.push(`CONSOLE: ${m.text().slice(0, 200)}`); });
await page.goto('http://localhost:5001/sign-in', { waitUntil: 'domcontentloaded', timeout: 20000 });
await page.waitForTimeout(6000);
const body = (await page.locator('body').innerText()).slice(0, 400);
console.log('BODY:', JSON.stringify(body));
const buttons = await page.locator('button').count();
console.log('buttons:', buttons);
console.log('errors:', errors.length ? errors.slice(0, 4) : 'none');
await browser.close();
