// Extracted from App.tsx
import type { ClimbingEvent } from '@workspace/api-client-react';
import { Globe, MapPin, Users } from 'lucide-react';
import { Avatar } from '@/components/avatar';


function EventCard({ event, onRsvp, pending }: { event: ClimbingEvent; onRsvp: () => void; pending: boolean }) {
  return <article data-testid={`card-event-${event.id}`} className="crew-card overflow-hidden rounded-[22px]"><div className="relative min-h-[170px] bg-secondary/50" style={event.imageUrl ? { backgroundImage: `linear-gradient(0deg, hsl(180 27% 15% / .65), transparent), url(${event.imageUrl})`, backgroundSize: 'cover', backgroundPosition: 'center' } : { backgroundImage: event.type === 'outdoor' ? 'linear-gradient(145deg, hsl(74 45% 59%), hsl(180 27% 15%))' : 'linear-gradient(145deg, hsl(14 49% 64%), hsl(43 25% 67%))' }}><div className="absolute left-4 top-4 flex items-center gap-1.5"><span className="rounded-full bg-sidebar px-3 py-1.5 font-mono text-[10px] uppercase tracking-widest text-sidebar-foreground">{event.type}</span><span className="flex items-center gap-1 rounded-full bg-sidebar/70 px-2.5 py-1.5 font-mono text-[10px] font-bold text-sidebar-foreground backdrop-blur">{event.visibility === 'crew-only' ? <><Users size={11} /> Crew only</> : <><Globe size={11} /> Public</>}</span></div><div className="absolute bottom-4 left-4 right-4 flex items-end justify-between text-sidebar-foreground"><div><p className="font-mono text-[11px] uppercase tracking-wider text-primary">{event.dateLabel}</p><p className="mt-1 text-sm font-bold">{event.timeLabel}</p></div><span className="rounded-full bg-sidebar/70 px-2.5 py-1 text-xs font-bold backdrop-blur">{event.attendees}/{event.spots}</span></div></div><div className="p-5 md:p-6"><h2 className="font-display text-2xl font-bold leading-tight tracking-[-.04em]">{event.title}</h2><p className="mt-2 flex items-center gap-1.5 text-sm text-muted-foreground"><MapPin size={14} />{event.location}</p><p className="mt-4 line-clamp-2 text-sm leading-relaxed text-foreground/70">{event.description}</p><div className="mt-5 flex items-center gap-2 border-t border-border pt-4"><Avatar profile={event.host} size="sm" /><span className="min-w-0 flex-1 text-xs"><span className="block text-muted-foreground">Hosted by</span><strong>{event.host.name}</strong></span><button data-testid={`button-rsvp-${event.id}`} disabled={pending} onClick={onRsvp} className={`rounded-full px-4 py-2.5 text-xs font-extrabold ${event.joined ? 'border border-border bg-card text-foreground' : 'bg-primary text-primary-foreground'}`}>{pending ? 'Saving…' : event.joined ? 'Going' : 'I’m in'}</button></div></div></article>;
}

export { EventCard };
