// Extracted from App.tsx
import { Link } from 'wouter';
import { ChevronRight, Heart, MapPin } from 'lucide-react';
import { Logo } from '@/components/logo';


function Home() {
  return (
    <div className="min-h-[100dvh] overflow-hidden bg-sidebar text-sidebar-foreground">
      <div className="absolute inset-0 opacity-40" style={{ backgroundImage: 'linear-gradient(125deg, transparent 0 52%, hsl(74 100% 69% / .12) 52% 53%, transparent 53% 100%), radial-gradient(circle at 84% 12%, hsl(14 49% 64% / .24), transparent 28%)' }} />
      <header className="relative z-10 flex items-center justify-between px-6 py-6 md:px-12"><Logo /><div className="flex items-center gap-5"><Link data-testid="link-home-sign-in" href="/sign-in" className="text-sm font-bold text-sidebar-foreground/70 hover:text-primary">Sign in</Link><Link data-testid="link-home-sign-up" href="/sign-in" className="rounded-full bg-primary px-4 py-2.5 text-sm font-extrabold text-primary-foreground transition-transform hover:-translate-y-0.5">Join the crew <ChevronRight className="ml-1 inline" size={15} /></Link></div></header>
      <section className="relative z-10 mx-auto grid max-w-[1280px] items-center gap-16 px-6 pb-24 pt-16 md:grid-cols-[1.05fr_.95fr] md:px-12 md:pb-32 md:pt-24">
        <div className="rise-in"><p className="mb-6 flex items-center gap-2 font-mono text-[11px] uppercase tracking-[.2em] text-primary"><span className="h-2 w-2 rounded-full bg-primary" /> climbing partners, not dating profiles</p><h1 className="max-w-3xl font-display text-[clamp(3.5rem,7.6vw,7.2rem)] font-bold leading-[.88] tracking-[-.075em]">Find your<br /><span className="text-primary">people.</span><br />Find your crew.</h1><p className="mt-8 max-w-lg text-lg leading-relaxed text-sidebar-foreground/65">A better way to share the wall, the rope, the road trip, or a quiet Tuesday session. Meet climbers who actually show up.</p><div className="mt-9 flex flex-wrap items-center gap-4"><Link data-testid="link-hero-start" href="/sign-in" className="crew-button rounded-full bg-primary px-6 py-3.5 text-sm font-extrabold text-primary-foreground">Start finding partners <ChevronRight className="ml-1 inline" size={16} /></Link><Link data-testid="link-hero-how" href="/events" className="text-sm font-bold text-sidebar-foreground/65 underline decoration-sidebar-foreground/25 underline-offset-8 hover:text-primary">See what’s happening nearby</Link></div></div>
        <div className="relative rise-in [animation-delay:120ms]"><div className="absolute -right-10 -top-9 h-32 w-32 rounded-full border border-primary/30" /><div className="relative mx-auto max-w-[470px] rotate-[3deg] rounded-[28px] border border-sidebar-foreground/10 bg-[#213b3a] p-3 shadow-2xl"><div className="overflow-hidden rounded-[21px] bg-[#c9c8ad]"><div className="flex aspect-[.88] items-end p-6" style={{ backgroundImage: 'linear-gradient(0deg, hsl(180 27% 15% / .75), transparent 63%), linear-gradient(135deg, hsl(14 49% 64% / .8), hsl(43 25% 67% / .5) 40%, hsl(74 54% 59% / .55))' }}><div><div className="mb-3 inline-flex rounded-full bg-primary px-3 py-1 font-mono text-[10px] font-bold uppercase tracking-wider text-primary-foreground">87% aligned</div><h2 className="font-display text-4xl font-bold tracking-tight text-sidebar-foreground">Maya, 29</h2><p className="mt-1 flex items-center gap-1 text-sm text-sidebar-foreground/75"><MapPin size={13} /> 2.4 mi · The Circuit</p></div></div></div><div className="mt-3 flex items-center justify-between px-2 pb-1"><span className="font-mono text-[10px] uppercase tracking-widest text-sidebar-foreground/45">boulder · lead · outdoors</span><Heart className="text-primary" size={18} fill="currentColor" /></div></div><div className="absolute -bottom-5 -left-5 flex items-center gap-3 rounded-2xl border border-sidebar-foreground/10 bg-sidebar-accent px-4 py-3 shadow-xl"><div className="flex -space-x-3"><span className="h-8 w-8 rounded-full border-2 border-sidebar-accent bg-[#d48467]" /><span className="h-8 w-8 rounded-full border-2 border-sidebar-accent bg-[#7c9a77]" /><span className="h-8 w-8 rounded-full border-2 border-sidebar-accent bg-[#d0b46e]" /></div><span className="text-xs font-bold">2,840 climbers nearby</span></div></div>
      </section>
      <section className="relative z-10 border-t border-sidebar-foreground/10 px-6 py-10 md:px-12"><div className="mx-auto grid max-w-[1280px] gap-8 md:grid-cols-3"><div><span className="font-display text-4xl font-bold text-primary">01</span><h3 className="mt-3 font-display text-xl font-bold">Share the real plan</h3><p className="mt-2 max-w-xs text-sm leading-relaxed text-sidebar-foreground/55">Tuesday boulders, a Smith Rock weekend, or finally learning to lead. Specific beats small talk.</p></div><div><span className="font-display text-4xl font-bold text-secondary">02</span><h3 className="mt-3 font-display text-xl font-bold">Meet on your terms</h3><p className="mt-2 max-w-xs text-sm leading-relaxed text-sidebar-foreground/55">Belay partner, crew hang, maybe more. You decide what the connection is open to.</p></div><div><span className="font-display text-4xl font-bold text-sidebar-foreground/30">03</span><h3 className="mt-3 font-display text-xl font-bold">Keep showing up</h3><p className="mt-2 max-w-xs text-sm leading-relaxed text-sidebar-foreground/55">Trusted profiles, shared gyms, and plans that turn into a regular thing.</p></div></div></section>
    </div>
  );
}

export { Home };
